version: '3'
services:
  credit-service:
    container_name: credit-calculator-api-container
    image: "${CONTAINER_REGISTRY_URL}/${CONTAINER_REGISTRY_USERNAME}/credit-calculator-api"
    environment:
      - "SERVER_PORT=${SERVER_PORT}"
      - "ALLOWED_ORIGINS=${ALLOWED_ORIGINS}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: [ 'CMD', 'curl', '-f','http://localhost:$SERVER_PORT/actuator/health' ]
      interval: 30s
      timeout: 5s
      retries: 5