version: '3'
services:
  credit-service:
    container_name: credit-calculator-api-container
    image: "${CONTAINER_REGISTRY_URL}/${CONTAINER_REGISTRY_USERNAME}/credit-calculator-api"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"