name: Build

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_PORT: ${{ vars.SERVER_PORT }}
      ALLOWED_ORIGINS: ${{ vars.ALLOWED_ORIGINS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Save Maven Cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save